"""create trials, outcomes, interventions, ingestion_runs

Revision ID: 4661dc6b7997
Revises:
Create Date: 2026-10-05 12:02:49.224868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4661dc6b7997'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('invalid', sa.Integer(), nullable=False),
    sa.Column('raw_uri', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index(op.f('ix_ingestion_runs_source'), 'ingestion_runs', ['source'], unique=False)
    op.create_table('trials',
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('brief_title', sa.Text(), nullable=False),
    sa.Column('official_title', sa.Text(), nullable=True),
    sa.Column('overall_status', sa.String(length=64), nullable=True),
    sa.Column('study_type', sa.String(length=64), nullable=True),
    sa.Column('phases', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('conditions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('lead_sponsor_name', sa.Text(), nullable=True),
    sa.Column('lead_sponsor_class', sa.String(length=32), nullable=True),
    sa.Column('enrollment_count', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('start_date_precision', sa.String(length=8), nullable=True),
    sa.Column('primary_completion_date', sa.Date(), nullable=True),
    sa.Column('primary_completion_date_precision', sa.String(length=8), nullable=True),
    sa.Column('primary_completion_type', sa.String(length=16), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('completion_date_precision', sa.String(length=8), nullable=True),
    sa.Column('results_first_submit_date', sa.Date(), nullable=True),
    sa.Column('results_first_post_date', sa.Date(), nullable=True),
    sa.Column('last_update_post_date', sa.Date(), nullable=True),
    sa.Column('has_results', sa.Boolean(), nullable=False),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('first_ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('nct_id', name=op.f('pk_trials'))
    )
    op.create_index(op.f('ix_trials_has_results'), 'trials', ['has_results'], unique=False)
    op.create_index(op.f('ix_trials_lead_sponsor_name'), 'trials', ['lead_sponsor_name'], unique=False)
    op.create_index(op.f('ix_trials_overall_status'), 'trials', ['overall_status'], unique=False)
    op.create_index(op.f('ix_trials_primary_completion_date'), 'trials', ['primary_completion_date'], unique=False)
    op.create_table('trial_interventions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['nct_id'], ['trials.nct_id'], name=op.f('fk_trial_interventions_nct_id_trials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trial_interventions')),
    sa.UniqueConstraint('nct_id', 'position', name=op.f('uq_trial_interventions_nct_id_position'))
    )
    op.create_index(op.f('ix_trial_interventions_name'), 'trial_interventions', ['name'], unique=False)
    op.create_index(op.f('ix_trial_interventions_nct_id'), 'trial_interventions', ['nct_id'], unique=False)
    op.create_table('trial_outcomes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('measure', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_frame', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nct_id'], ['trials.nct_id'], name=op.f('fk_trial_outcomes_nct_id_trials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trial_outcomes')),
    sa.UniqueConstraint('nct_id', 'kind', 'position', name=op.f('uq_trial_outcomes_nct_id_kind_position'))
    )
    op.create_index(op.f('ix_trial_outcomes_nct_id'), 'trial_outcomes', ['nct_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trial_outcomes_nct_id'), table_name='trial_outcomes')
    op.drop_table('trial_outcomes')
    op.drop_index(op.f('ix_trial_interventions_nct_id'), table_name='trial_interventions')
    op.drop_index(op.f('ix_trial_interventions_name'), table_name='trial_interventions')
    op.drop_table('trial_interventions')
    op.drop_index(op.f('ix_trials_primary_completion_date'), table_name='trials')
    op.drop_index(op.f('ix_trials_overall_status'), table_name='trials')
    op.drop_index(op.f('ix_trials_lead_sponsor_name'), table_name='trials')
    op.drop_index(op.f('ix_trials_has_results'), table_name='trials')
    op.drop_table('trials')
    op.drop_index(op.f('ix_ingestion_runs_source'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
