"""add faers drugs, trial drug links, drug event stats

Revision ID: eae6f75d1de9
Revises: efcebeb722f7
Create Date: 2026-10-05 18:13:10.421006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae6f75d1de9'
down_revision: Union[str, Sequence[str], None] = 'efcebeb722f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faers_drugs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('query_term', sa.Text(), nullable=False),
    sa.Column('match_field', sa.String(length=32), nullable=True),
    sa.Column('total_reports', sa.BigInteger(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faers_drugs')),
    sa.UniqueConstraint('query_term', name=op.f('uq_faers_drugs_query_term'))
    )
    op.create_table('faers_drug_event_stats',
    sa.Column('drug_id', sa.BigInteger(), nullable=False),
    sa.Column('reaction_pt', sa.Text(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('a', sa.BigInteger(), nullable=False),
    sa.Column('n_drug', sa.BigInteger(), nullable=False),
    sa.Column('n_event', sa.BigInteger(), nullable=False),
    sa.Column('n_total', sa.BigInteger(), nullable=False),
    sa.Column('prr', sa.Float(), nullable=True),
    sa.Column('ror', sa.Float(), nullable=True),
    sa.Column('ror_ci_low', sa.Float(), nullable=True),
    sa.Column('ror_ci_high', sa.Float(), nullable=True),
    sa.Column('chi2', sa.Float(), nullable=True),
    sa.Column('is_signal', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['faers_drugs.id'], name=op.f('fk_faers_drug_event_stats_drug_id_faers_drugs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drug_id', 'reaction_pt', 'snapshot_date', name=op.f('pk_faers_drug_event_stats'))
    )
    op.create_index(op.f('ix_faers_drug_event_stats_is_signal'), 'faers_drug_event_stats', ['is_signal'], unique=False)
    op.create_table('trial_drug_links',
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('drug_id', sa.BigInteger(), nullable=False),
    sa.Column('intervention_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['faers_drugs.id'], name=op.f('fk_trial_drug_links_drug_id_faers_drugs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nct_id'], ['trials.nct_id'], name=op.f('fk_trial_drug_links_nct_id_trials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nct_id', 'drug_id', name=op.f('pk_trial_drug_links'))
    )
    op.create_index(op.f('ix_trial_drug_links_drug_id'), 'trial_drug_links', ['drug_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trial_drug_links_drug_id'), table_name='trial_drug_links')
    op.drop_table('trial_drug_links')
    op.drop_index(op.f('ix_faers_drug_event_stats_is_signal'), table_name='faers_drug_event_stats')
    op.drop_table('faers_drug_event_stats')
    op.drop_table('faers_drugs')
    # ### end Alembic commands ###
