"""add publications, trial_publication_links, ingestion run stats

Revision ID: efcebeb722f7
Revises: 4661dc6b7997
Create Date: 2026-10-05 17:15:06.587219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efcebeb722f7'
down_revision: Union[str, Sequence[str], None] = '4661dc6b7997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('pmid', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('journal', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('pub_date_precision', sa.String(length=8), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('publication_types', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('registry_ids', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('first_ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pmid', name=op.f('pk_publications'))
    )
    op.create_table('trial_publication_links',
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('pmid', sa.String(length=16), nullable=False),
    sa.Column('link_source', sa.String(length=32), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nct_id'], ['trials.nct_id'], name=op.f('fk_trial_publication_links_nct_id_trials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nct_id', 'pmid', 'link_source', name=op.f('pk_trial_publication_links'))
    )
    op.create_index(op.f('ix_trial_publication_links_pmid'), 'trial_publication_links', ['pmid'], unique=False)
    op.add_column('ingestion_runs', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs', 'stats')
    op.drop_index(op.f('ix_trial_publication_links_pmid'), table_name='trial_publication_links')
    op.drop_table('trial_publication_links')
    op.drop_table('publications')
    # ### end Alembic commands ###
